OPEN_PERMISSION_READ = "r"
OPEN_PERMISSION_WRITE = "w"

INT_ZERO = 0
INT_ONE = 1
INT_TWO = 2
INT_TEN = 10
INT_ONE_HUNDRED = 100
INT_ONE_HUNDRED_THOUSAND = 100000
FLOAT_TEN = 10.0

CHAR_PERCENTAGE = "%"
EMPTY_STR = ""
EMPTY_LIST = []
EMPTY_DICTIONARY = {}

FIRST_GROUP_INDEX = 1
LIST_ELEMENT_INDEX_FIRST = 0
LIST_ELEMENT_INDEX_LAST = -1

HTML_PARSER = "html.parser"
STR_VALUE_DUMMY = "dummy"

MANGA4LIFE_KEYWORD_EMAILADDRESS = "EmailAddress"
MANGA4LIFE_KEYWORD_PASSWORD = "Password"
MANGA4LIFE_LOGIN_PAYLOAD = {
    MANGA4LIFE_KEYWORD_EMAILADDRESS: "dummy",
    MANGA4LIFE_KEYWORD_PASSWORD: "dummy",
}

MANGA4LIFE_LITERAL_SUCCESS = "success"
MANGA4LIFE_LITERAL_VAL = "val"
MANGA4LIFE_LITERAL_OK = "ok"
MANGA4LIFE_LITERAL_CHAPTER = "Chapter"
MANGA4LIFE_LITERAL_INDEXNAME = "IndexName"
MANGA4LIFE_LITERAL_DATE = "Date"
MANGA4LIFE_LITERAL_SCRIPT = "script"

MANGA4LIFE_REGEX_SEARCH = "vm.FeedJSON = (.*?);"
MANGA4LIFE_FORMAT_CHAPTER_URL = (
    "{dateEntry} {prefix_url}{indexName}-chapter-{chapter_no}.html"
)

MANGA4LIFE_URL_LOGIN = "https://manga4life.com/auth/login.php"
MANGA4LIFE_URL_READ = "https://manga4life.com/read-online/"
MANGA4LIFE_URL_FEED = "https://manga4life.com/feed.php"

SALEPRICE_REGEX_DIGIT_ONLY = r"\d+"
SALEPRICE_KEYWORD_ID = "id"
SALEPRICE_KEYWORD_PRICE = "price"
SALEPRICE_KEYWORD_NAME = "name"
SALEPRICE_KEYWORD_UPDATE = "update"
SALEPRICE_KEYWORD_PERCENTAGE = "percentage"
SALEPRICE_TIME_FORMAT = "%Y-%m-%d_%H-%M-%S"

SALEPRICE_LOG_DBG_001 = "Scrape for id: {product_id}"

CELLPHONES_URL_BASE = "https://cellphones.com.vn/"
CELLPHONES_DATABASE_NAME = "cellphones"
CELLPHONES_PRODUCT_SUFFIX = ".html"
CELLPHONES_SALEPRICE_ELEMENT = "p"
CELLPHONES_SALEPRICE_PROPERTY = {"class": "product__price--show"}
CELLPHONES_NAME_ELEMENT = "div"
CELLPHONES_NAME_PROPERTY = {"class": "box-product-name"}

GEARVN_URL_BASE = "https://gearvn.com/"
GEARVN_DATABASE_NAME = "gearvn"
GEARVN_PRODUCT_URL_EXT = "products/"
GEARVN_SALEPRICE_ELEMENT = "span"
GEARVN_SALEPRICE_PROPERTY = {"class": "product_sale_price"}
GEARVN_NAME_ELEMENT = "h1"
GEARVN_NAME_PROPERTY = {"class": "product_name"}
